#!/bin/bash

# --------------------
# CONFIGURATION
# --------------------
GITHUB_REPO="vramprasad/base-images"       # e.g. myuser/myrepo
NEW_BRANCH="renovate-$(date +%Y%m%d%H%M%S)"
CLONE_DIR="/tmp/$(basename "$GITHUB_REPO")"
COMMIT_MSG="Update Dockerfile ARGs: auto-generated by Renovate"
PR_TITLE="Update Dockerfile by Renovate"
PR_BODY="This PR updates package versions values in the Dockerfile automatically. This PR is created by Renovate Bot. Please review and merge if everything looks good."

# --------------------
# FUNCTION: Update ARG or ENV in Dockerfile
# Usage: update_dockerfile_arg TAR_VERSION 1.35
# --------------------
update_dockerfile_arg() {
  local key="$1"
  local new_value="$2"

  if grep -qE "^(ARG|ENV)[[:space:]]+$key=" Dockerfile; then
    echo "Updating $key to $new_value in Dockerfile..."
    sed -i -E "s|^(ARG|ENV)[[:space:]]+$key=.*|\1 $key=$new_value|" Dockerfile
  else
    echo "Appending $key=$new_value to Dockerfile..."
    echo "ARG $key=$new_value" >> Dockerfile
  fi
}

# --------------------
# STEP 1: Clone the repo
# --------------------
echo "Cloning repository..."
rm -rf "$CLONE_DIR"
git clone "https://github.com/${GITHUB_REPO}.git" "$CLONE_DIR"
cd "$CLONE_DIR" || exit 1

# --------------------
# STEP 2: Create new branch
# --------------------
echo "Creating branch $NEW_BRANCH..."
git checkout -b "$NEW_BRANCH"

# --------------------
# STEP 3: Update Dockerfile values
# --------------------
echo "Updating Dockerfile ARG/ENV values..."
update_dockerfile_arg TAR_VERSION "1.35"
update_dockerfile_arg GZIP_VERSION "1.13"

# --------------------
# STEP 4: Commit and push
# --------------------
echo "Committing changes..."
git add Dockerfile
git commit -m "$COMMIT_MSG"
git push origin "$NEW_BRANCH"

# --------------------
# STEP 5: Create PR using GitHub CLI
# --------------------
echo "Creating pull request..."
gh pr create \
  --title "$PR_TITLE" \
  --body "$PR_BODY" \
  --head "$NEW_BRANCH" \
  --base "$(gh repo view --json defaultBranchRef -q .defaultBranchRef.name)"

echo "✅ Done! Pull request created."
